<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByMail($email)
    {
        return $this->getEntityManager()
            ->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.uEmail = :email'
        )->setParameter('email', $email)
         ->setMaxResults(1)->getOneOrNullResult();
    }
}
